### ISSUE TITLE
Documentation??

### ISSUE THREAD

**Issue by GreenJoey** [jelly/pyalpm#1]
Where can I <em><strong>find documentation??</strong></em>

**Comment by jelly** [comment]
What kind of documentation are you looking for? What are you trying to achieve? There are some examples in scripts.

I'll see if I can setup documentation with sphinx.

**Comment by jelly** [comment]
btw the official repo is: https://git.archlinux.org/pyalpm.git/

**Comment by GreenJoey** [comment]
I am trying to create a libalpm entirely written in python with some extra features. So that why I looking doc??

**Comment by jelly** [comment]
You can't easily write an libalpm fully in Python since the libalpm libs are in C. Even with CFFI you can't get away with writing C. Documentation will be provided later, but I can't promise anytime soon.

**Comment by GreenJoey** [comment]
No, No libalpm. I am talking about pacman in python

**Comment by jelly** [comment]
Ok, then just read the pacman source code.
