### ISSUE TITLE
Can't run with LANG=C

### ISSUE THREAD

**Issue by 71e6fd52** [jelly/pyalpm#3]
I use powerpill with `LANG=C` and it is fail
```
File "/usr/lib/python3.6/site-packages/pycman/config.py", line 92, in pacman_conf_enumerator
line = f.readline()
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 80: ordinal not in range(128)
```

powerpill's devs Xyne let me to report it to the pyalpm devs (https://bbs.archlinux.org/viewtopic.php?pid=1736772)

There's my pacman.conf: https://fars.ee/tnBy.conf

**Comment by Kwpolska** [comment]
Try changing [line 89 of /usr/lib/python3.6/site-packages/pycman/config.py](https://github.com/jelly/pyalpm/blob/master/pycman/config.py#L89) to this:

```py
	filestack.append(open(path, 'r', encoding='utf-8'))
```

However, I can’t see any offending non-ASCII characters in your pacman.conf. Does this fix it for you?

**Comment by 71e6fd52** [comment]
NO

**Comment by 71e6fd52** [comment]
hello?

**Comment by jelly** [comment]
Yes, hello, I can't reproduce the issue.

**Comment by jelly** [comment]
And this also works fine:
```
[jelle@lithium][/tmp/powerpill]%LANG=C sudo powerpill --config /tmp/tnBy.conf -Syu
```

**Comment by 71e6fd52** [comment]
http://fars.ee/t/h2vi.json

**Comment by 71e6fd52** [comment]
In my conf:
```
[archlinuxcn]
Include = /etc/pacman.d/archlinuxcn-mirrorlist
```
and `archlinuxcn-mirrorlist` is include **Chinese**

**Comment by 71e6fd52** [comment]
And I changed [L113](https://github.com/jelly/pyalpm/blob/master/pycman/config.py#L113) to fix it
