### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by jayvdb** [jelly/pyalpm#9]
https://github.com/jelly/pyalpm/releases shows it is out of date.

But more importantly https://git.archlinux.org/pyalpm.git/ is missing a tag for 0.8.5 which is the latest release on https://pypi.org/project/pyalpm/

**Comment by jayvdb** [comment]
Also it would be nice if the tests were included in the PyPI sdist, so packagers didnt need to use SCM tags to get the tests.

And wheels on PyPI might be a good idea.

**Comment by jelly** [comment]
This is not the official repository for pyalpm. It's hosted at https://github.com/archlinux/pyalpm
